### PR TITLE
fixed the computed state reading in template

### PR DESCRIPTION
**Pull request by davidmeirlevy**

### CODE REVIEW

**Comment by SungGyunKim** [comment]
매우 매우 감사합니다.
너의 수정한 소스를 확인할 수 있습니다.
왜  "Destructuring assignment"을 하기 위해 "spread operator"을 사용할 수 없는 건가요?

**Comment by SungGyunKim** [comment]
Thank you very much.
You can check your modified source.
Why can't I use the "spread operator" to do the "Destructuring assignment"?

**Comment by davidmeirlevy** [comment]
On Vue templates, if you have an object (let's say x) that looks like:

const x = {
 a: ref()
}

And then you want to use x.a  inside your template like that:
<div>{{ x.a }} </div>

This won't work.

**Comment by SungGyunKim** [comment]
Your kind reply has solved my frustration in the past.

I thought that x.a would be a Reactivity variable, but it doesn't.

const x = reactive({
  a : ref()
});

Can't I do this?

I'll try this.

**Comment by davidmeirlevy** [comment]
Hmm never actually tested it like that 😀 

Try and tell me 🙏

**Comment by davidmeirlevy** [comment]
please label this pr AS `hacktoberfest` :)

**Pull request merged**
